// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("lsbeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy0WE1vGzkSvetXFHLaBaTGxt4YCx0W47GNiTBxYkycs1IiSy2Ou8kOi21Z8+sHJPtTan041vhkfr33SFa9ono0gSfaTGFB6EYATrmMpvBrbEliYVXhlNFT+P8IAODGaIdKMwiT50aHdbBUlEkGfEaV4SIjUBowy4CeSTtwm4I4GUE1bToKQBPQmFMkTvy/oXeQ0/89rigsALMEt6KgEJi0VDoNHZlJISdmTIkTmHVmhWWKGygm5wX6cWH0UqWlRU8HS5XR2Pf7QXTwjFnpV0LJJAOmcr6pjeuChSWwMuwqpmr+owlUPR1jPxa6vvvm9wbHhB3v15XsHlrNePzgGm3IYMmVVpOExSZQmYI8jU6BN+woB6NhvVJi1QrvnJ0ttVY6HVDjVE5/GX2CmnrmP6nmmSwro4+LqSbWYRXCOVx+StpLIQlupTiGctIP3Xe/+K2ww7x4V4H6WJ+CRFefg6UfpbIkp+BsWXcujc3R9ebRC+aFT73rMi3ZwcWVW8HFf95fjeH9xfTyw/TDZXJ5eXHa6QZJsI6BTFUa+gSxJIyVsEZu97e1KYcpH2a5tgvlLNpNmBtPS6C3ghDvBdl4UahlaDiLmlG49j7iOW0RR3fonaNZ/EmizrXYmMeRJ9qsjZWHhTZeVTLZNqe8QUWyLQVkrbE9Aak1ZXGY5M4vqh1QREYfvyil8nMxA6WXxme2QA7+FXg4qYOhcsUasFZTmVnTX2ty9OI6nXtktdIqnGSHQBi5i54Znb4G3YPsQnusHej+nZ2EHsOkKlEiM6Vsa9SNb0JhzbOS5LfpUKLD4bJ1X43C0po8IjVL2d9Va0Eo5TxMmNeQfqYgZmP3VjE/NQmrkhp2O7FJHMnez53y1leYwINhVj5wQ01iQEsecAypoDEYC1KlymFmBKFO9mpTmh1qQXN1JHVm1USY3daSfBGBHMVK6e3UHWI4Xpkajm5dP42lmjDvxFlzzu4iyUmqMj/Mfh8hQoi9jrx65qhMuc28U/IaBSVPCNlN3osjRtoBglARVVvtFEc5itsydyDkgjc2t9pIqUYmL6eHXrXEa/nNmDSjmGn72S2lR0vtH2HOsf1ViS6NeAr5U2X6bd0eAI9jwA6dt98sI+FrdkjzOOZzllfGunmsAFNYYsb+0lCLlbE136TJ8lHflOstN7JgsD7s8/GqJpBNlHybJ37T6kdJLSAoOeTqDV0+VD5exdiNiwBXv04rAf4hsShV5sDoQ1I6ZvCTSm4aTo91iCvDBWW8w9Z7S8Dh98QRLbNwEpGnCVofzG3IfoytAZCZfwx0AtVXuR3raWPT9x+NzIr7dXH59jv5WP2s2L2NM0V6NIiBIEcrVsqRcKU9wx56cPAvStIEXv53Nb/67xjQ5mMoCjGGXBX8710phpMiQ+ef9G9T8uUr1ECVBkHaGR5DuSi1K8ewVlqa9R4R/V88P6+hwhnkWGKuss2bKSJMtUlLcoVuDJIWCvUYlpZowfLQblWxI6HXdYD9k2LnDW32MEEpLTET7xLkKN62yZpmhVau0VJLNoaSS8yyDdxf33Q11D7yVC7IanLErZv83u0boG3Hm2dw/03bgkLXSw6XxXbRUQPqiYZX2VBh5BnKQ+cECiOjtw1SlW+1pi0mjzdorVygON+mWsRdMv8L7Kwn6BH3HOGpxfU0oogGORa7TKi1ceH719noOpDDnOd8sHR4Re/tcoj2DE+2Qd6IWzlMxv2PvU27i7on0YUptdt6BHc+GQx+7doj9uHT3fXXO/j2cHv9eAe3X26+3d99frx+nH35PPo7AAD//0JdmaI="
}
